# Develop using a known working environment.
# @usage
# run `make dev_container`
FROM ocaml/opam:ubuntu-18.04-ocaml-4.13
USER root
# https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash \
  && apt-get update \
  && apt-get install -y libgmp-dev pkg-config nodejs
USER opam
RUN opam install --deps-only \
  js_of_ocaml \
  js_of_ocaml-compiler \
  js_of_ocaml-lwt \
  js_of_ocaml-ocamlbuild \
  js_of_ocaml-ppx \
  js_of_ocaml-ppx_deriving_json \
  js_of_ocaml-toplevel \
  js_of_ocaml-tyxml
RUN opam install \
  cohttp-lwt-unix \
  graphics \
  lwt \
  menhir \
  ocp-indent \
  ppx_expect \
  ppxlib \
  reactiveData \
  sexplib \
  tyxml \
  yojson
