lib: [
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/ocamlbuild_js_of_ocaml.cmxs"
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/ocamlbuild_js_of_ocaml.a"
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/ocamlbuild_js_of_ocaml.cmxa"
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/ocamlbuild_js_of_ocaml.cma"
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/ocamlbuild_js_of_ocaml.mli"
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/ocamlbuild_js_of_ocaml.cmti"
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/ocamlbuild_js_of_ocaml.cmt"
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/ocamlbuild_js_of_ocaml.cmx"
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/ocamlbuild_js_of_ocaml.cmi"
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/opam" {"opam"}
  "_build/install/default/lib/js_of_ocaml-ocamlbuild/META" {"META"}
]
doc: [
  "_build/install/default/doc/js_of_ocaml-ocamlbuild/CHANGES"
  "_build/install/default/doc/js_of_ocaml-ocamlbuild/LICENSE"
  "_build/install/default/doc/js_of_ocaml-ocamlbuild/README.md"
]
