lib: [
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js.cmxs"
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js.a"
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js.cmxa"
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js.cma"
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js.ml"
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js.cmt"
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js.cmx"
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js.cmi"
  "_build/install/default/lib/js_of_ocaml-ppx/ppx_js" {"ppx_js"}
  "_build/install/default/lib/js_of_ocaml-ppx/opam" {"opam"}
  "_build/install/default/lib/js_of_ocaml-ppx/META" {"META"}
]
