lib: [
  "_build/install/default/lib/js_of_ocaml-camlp4/pa_js.cmxs"
  "_build/install/default/lib/js_of_ocaml-camlp4/pa_js.a"
  "_build/install/default/lib/js_of_ocaml-camlp4/pa_js.cmxa"
  "_build/install/default/lib/js_of_ocaml-camlp4/pa_js.cma"
  "_build/install/default/lib/js_of_ocaml-camlp4/pa_js.ml"
  "_build/install/default/lib/js_of_ocaml-camlp4/pa_js.cmt"
  "_build/install/default/lib/js_of_ocaml-camlp4/pa_js.cmx"
  "_build/install/default/lib/js_of_ocaml-camlp4/pa_js.cmi"
  "_build/install/default/lib/js_of_ocaml-camlp4/opam" {"opam"}
  "_build/install/default/lib/js_of_ocaml-camlp4/META" {"META"}
]
