
# Where binaries are installed:
BINDIR := /usr/local/bin

####

LIBRARY  := js_of_ocaml
LIBNAME  := js_of_ocaml$(LIBEXT)
COMPILER := js_of_ocaml$(EXEEXT)
MINIFIER := jsoo_minify$(EXEEXT)
# opt/byte
BEST := opt

####

EXEEXT :=
OBJEXT := .o
LIBEXT := .a
DLLEXT := .so

ifeq ($(shell ocamlc -v | grep -q "version 4"; echo $$?),0)
OCAML4:="YES"
endif

### Optional dependencies: deriving
WITH_DERIVING := $(shell ocamlfind query deriving 2> /dev/null)


WITH_GRAPHICS := $(shell ocamlfind query graphics 2> /dev/null)


NATDYNLINK := $(shell if [ -f `ocamlc -where`/dynlink.cmxa ]; then echo YES; else echo NO; fi)

METAOCAML ?= 0

VERSION_GIT := $(shell git log -n1 --pretty=format:%h 2> /dev/null)
