
include ../Makefile.conf

COMP=../compiler/$(COMPILER)
JSFILES=../runtime/runtime.js file/unix.js
OCAMLC=ocamlfind ocamlc $(SAFESTRING) -package lwt,deriving -ppx ../lib/ppx/ppx_js.byte ../lib/syntax/pa_deriving_Json.cmo -I ../lib -I ../lib/deriving_json
STDLIB=$(LIBNAME).cma


%.js: %.byte $(COMP) $(JSFILES)
	@$(COMP) --no-runtime $(JSFILES) $< $(OPTIONS) --pretty

%.byte: %.cmo
	@$(OCAMLC) -linkpkg -o $@ $(STDLIB) ../lib/deriving_json.cma common.cmo -package unix $^

%.cmo: %.ml ../lib/$(STDLIB)
	@$(OCAMLC) -g -c $<
