// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cmo, use-js-string=true, version=5.4.0+git-5.2.0-99-g50bcd077-dirty

//# unitInfo: Provides: Dead_field
//# unitInfo: Requires: Stdlib
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   var
    _d_ = undefined,
    global_data = runtime.caml_get_global_data(),
    Stdlib = global_data.Stdlib;
   function _a_(_f_, _e_){
    var _g_ = _f_ ? [0, 1, _d_, _e_] : [0, 3, _d_, 4];
    return [0, _g_[1], _g_[3]];
   }
   var _b_ = _a_(0, 2)[2], _c_ = _a_(1, 1)[1] + _b_ | 0;
   caml_call1(Stdlib[44], _c_);
   var Dead_field = [0];
   runtime.caml_register_global(1, Dead_field, "Dead_field");
   return;
  }
  (globalThis));
