(* Js_of_ocaml compiler
 * http://www.ocsigen.org/js_of_ocaml/
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, with linking exception;
 * either version 2.1 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *)

(** Runtime of [ppx_expect_light]: a small, self-contained reimplementation of
    the [%expect] machinery with support for environment-conditional snapshots
    ([%expect.when]) and tag-based skipping ([@tags]).

    All values here are called by code generated by the [ppx_expect_light]
    rewriter; they are not meant to be used directly. *)

(** Runtime axes ([backend]/[engine]/...) referenced by reified
    [%expect.when] conditions. *)
module Axes : module type of Axes

(** One environment-specific variant of an [%expect] assertion point. *)
type variant =
  { condition : unit -> bool (* reified [%expect.when] predicate *)
  ; is_default : bool (* [true] for a plain [%expect] with no [.when] *)
  ; expected : string (* contents of the [{| ... |}] literal *)
  ; payload_start : int (* byte offset of the literal token in the source *)
  ; payload_end : int (* byte offset just past the literal token *)
  }

(** Register an [let%expect_test]. [expectations] holds one group of [variant]s
    per assertion point (in source order); [check ~index:k] refers to group
    [k]. *)
val register_test :
     filename:string
  -> description:string
  -> line_number:int
  -> tags:string list
  -> expectations:variant array array
  -> (unit -> unit)
  -> unit

(** Called at each [%expect]/[%expect.when] point: compares the output captured
    since the previous point against the active variant of group [index]. *)
val check : index:int -> unit

(** Called for [%expect.output]: returns (and consumes) the output captured
    since the previous expect point. *)
val read_output : unit -> string

(** Entry point of the generated inline-test runner. Parses the runner CLI, runs
    the registered tests under output capture, writes [.corrected] files for
    mismatches and exits with a non-zero status on failure. *)
val exit : unit -> unit
