
OCAML2JS=../../ocaml2js
JSFILES=../../runtime/runtime.js
OCAMLC=ocamlfind ocamlc -package lwt -pp "camlp4o ../../lib/pa_js.cmo" -I ../../lib
STDLIB=ocaml2js.cma

$(NAME).js: $(NAME) $(OCAML2JS) $(JSFILES)
	$(OCAML2JS) $(JSFILES) $(NAME) $(OPTIONS)

$(NAME): $(OBJS)
	$(OCAMLC) -linkpkg -o $@ $(STDLIB) $^

%.cmo: %.ml ../../lib/ocaml2js.cma
	$(OCAMLC) -g -c $<

clean:
	rm -f *.cm[io] $(NAME) $(NAME).js
