include ../../Makefile.conf

COMP=../../compiler/$(COMPILER)
JSFILES=../../runtime/runtime.js file/unix.js
OCAMLC=ocamlfind ocamlc $(SAFESTRING) -package lwt,deriving -ppx ../../ppx/ppx_js/bin/ppx_js.byte -I ../../lib -I ../../lib/deriving_json
STDLIB=$(LIBRARY).cma


%.js: %.byte $(COMP) $(JSFILES)
	$(COMP) --no-runtime $(JSFILES) $< $(OPTIONS) --pretty

%.cmo: %.ml ../../lib/$(STDLIB)
	$(OCAMLC) -g -c $<
