// Generated by js_of_ocaml
//# buildInfo:effects=cps, kind=cmo, toplevel=true, use-js-string=true, version=6.4.1+daca709

//# unitInfo: Provides: Test_dynlink
//# unitInfo: Requires: Stdlib
//# shape: Test_dynlink:[F(1)]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    cst_base64 =
      runtime.caml_jsbytes_of_base64
       ("Q2FtbDE5OTlJMDM2hJWmvQpjdBpiXCi1L/0AWNUCANQEoCxUZXN0X2R5bmxpbmugsKAhZgEBFdDAwUDAs5CjJHVuaXRGQJBAAgX14QBAAPz9/kCwwDEuL3QubWxDZGjABBdDZGlAQLEEAUBBQEADAFQwHBTBjvTUA4SVpr4AAABqAAAADwAAADoAAAAuoKAsVGVzdF9keW5saW5rkDDdflT/CqUKWK6tLT2pBE9woKAmU3RkbGlikDB5KbW7XS+gf0jQHEyLgB1uoKA4Q2FtbGludGVybmFsRm9ybWF0QmFzaWNzkDBfyzQZCmK9dHlMCrkshQjFQISVpr4AAAAEAAAAAgAAAAUAAAAFoJBAQA");
   function caml_trampoline_cps_call2(f, a0, a1){
    return runtime.caml_stack_check_depth()
            ? (f.l
                >= 0
                ? f.l
                : f.l = f.length)
              === 2
              ? f(a0, a1)
              : runtime.caml_call_gen(f, [a0, a1])
            : runtime.caml_trampoline_return(f, [a0, a1], 0);
   }
   runtime.jsoo_create_file("/static/cmis/test_dynlink.cmi", cst_base64);
   var Stdlib = runtime.caml_get_global("Stdlib");
   runtime.caml_callback(Stdlib[46], ["Dynlink OK"]);
   var
    Test_dynlink =
      [0,
       function(a, cont){
        return caml_trampoline_cps_call2
                (Stdlib[46], "Test_dynlink.f Ok", cont);
       }];
   runtime.caml_register_global(Test_dynlink, "Test_dynlink");
   return;
  }
  (globalThis));
