// Generated by js_of_ocaml
//# buildInfo:effects=cps, kind=cmo, toplevel=true, use-js-string=true, version=6.4.1+e82c157

//# unitInfo: Provides: Test_dynlink
//# unitInfo: Requires: Stdlib
//# shape: Test_dynlink:[F(1)]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_trampoline_cps_call2(f, a0, a1){
    return runtime.caml_stack_check_depth()
            ? (f.l
                >= 0
                ? f.l
                : f.l = f.length)
              === 2
              ? f(a0, a1)
              : runtime.caml_call_gen(f, [a0, a1])
            : runtime.caml_trampoline_return(f, [a0, a1], 0);
   }
   runtime.jsoo_create_file
    ("/static/cmis/test_dynlink.cmi",
     "Caml1999I036\x84\x95\xa6\xbd\nct\x1ab\\(\xb5/\xfd\0X\xd5\x02\0\xd4\x04\xa0,Test_dynlink\xa0\xb0\xa0!f\x01\x01\x15\xd0\xc0\xc1@\xc0\xb3\x90\xa3$unitF@\x90@\x02\x05\xf5\xe1\0@\0\xfc\xfd\xfe@\xb0\xc01./t.mlCdh\xc0\x04\x17Cdi@@\xb1\x04\x01@A@@\x03\0T0\x1c\x14\xc1\x8e\xf4\xd4\x03\x84\x95\xa6\xbe\0\0\0j\0\0\0\x0f\0\0\0:\0\0\0.\xa0\xa0,Test_dynlink\x900\xdd~T\xff\n\xa5\nX\xae\xad-=\xa9\x04Op\xa0\xa0&Stdlib\x900y)\xb5\xbb]/\xa0\x7fH\xd0\x1cL\x8b\x80\x1dn\xa0\xa08CamlinternalFormatBasics\x900_\xcb4\x19\nb\xbdtyL\n\xb9,\x85\b\xc5@\x84\x95\xa6\xbe\0\0\0\x04\0\0\0\x02\0\0\0\x05\0\0\0\x05\xa0\x90@@");
   var Stdlib = runtime.caml_get_global("Stdlib");
   runtime.caml_callback(Stdlib[46], ["Dynlink OK"]);
   var
    Test_dynlink =
      [0,
       function(a, cont){
        return caml_trampoline_cps_call2
                (Stdlib[46], "Test_dynlink.f Ok", cont);
       }];
   runtime.caml_register_global(Test_dynlink, "Test_dynlink");
   return;
  }
  (globalThis));
