.\" Pipe this output to groff -Tutf8 | less
.\"
.mso an.tmac
.TH "JS_OF_OCAML-BUILD-FS" 1 "" "Js_of_ocaml 3.5.2+git-fb9dd20f6" "Js_of_ocaml Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
js_of_ocaml\N'45'build\N'45'fs \N'45' Js_of_ocaml pseudo filesystem utility
.SH SYNOPSIS
.P
\fBjs_of_ocaml build\N'45'fs\fR [\fIOPTION\fR]\N'46'\N'46'\N'46' [\fIFILES\fR]\N'46'\N'46'\N'46'
.SH DESCRIPTION
.P
jsoo_fs is a tool for embeding files in a Js_of_ocaml pseudo filesystem\N'46'
.SH ARGUMENTS
.TP 4
\fIFILES\fR
Embed [\fIFILES\fR] in the js_of_ocaml pseudo filesystem\N'46'
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=auto)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of `auto\N'39', `pager\N'39', `groff\N'39' or `plain\N'39'\N'46' With `auto\N'39', the format is `pager` or `plain\N'39' whenever the \fBTERM\fR env var is `dumb\N'39' or undefined\N'46'
.TP 4
\fB\N'45'I\fR \fIDIR\fR
Add [\fIDIR\fR] to the list of include directories\N'46'
.TP 4
\fB\N'45'o\fR \fIFILE\fR (required)
Set output file name to [\fIFILE\fR]\N'46'
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH BUGS
.P
Bugs are tracked on github at \fIhttps://github\N'46'com/ocsigen/js_of_ocaml/issues\fR\N'46'
.SH SEE ALSO
.P
ocaml(1)
.SH AUTHORS
.P
Jerome Vouillon, Hugo Heuzard\N'46'
.SH LICENSE
.P
Copyright (C) 2010\N'45'2020\N'46'
.P
js_of_ocaml is free software, you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, with linking exception; either version 2\N'46'1 of the License, or (at your option) any later version\N'46'